name: 编译并部署

on:
  workflow_dispatch:

jobs:
  complie:
    name: 编译
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        version: ['v1', 'v2']
    steps:
      - uses: actions/checkout@v4
        with:
          token:  ${{ secrets.GH_TOKEN }}
          ref: ${{ matrix.version }}
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install mike==1.1.2
          python -m pip install --upgrade pip setuptools wheel
      - name: Config Git
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
      - name: Build
        run: |
          git fetch origin deploy:deploy
          mike deploy --push --branch deploy --rebase ${{ matrix.version }}
          if [[ ${{ matrix.version }} == "v2" ]]; then
            mike set-default -b deploy ${{ matrix.version }}
          fi

  deploy:
    name: 部署
    runs-on: ubuntu-latest
    needs: complie
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: deploy
      - name: tar
        run: |
          rm -rf docs.tar*
          tar -zcf docs.tar.gz --exclude=.git *
          ls -la
      - name: upload
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.MAXKB_DOCS_HOST }}
          username: ${{ secrets.MAXKB_DOCS_HOST_USERNAME }}
          port: 22
          key: ${{ secrets.MAXKB_DOCS_HOST_KEY }}
          source: "docs.tar.gz"
          target: /tmp
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MAXKB_DOCS_HOST }}
          username: ${{ secrets.MAXKB_DOCS_HOST_USERNAME }}
          key: ${{ secrets.MAXKB_DOCS_HOST_KEY }}
          port: 22
          script: |
            set -e
            cd /tmp
            rm -rf docs
            mkdir -p docs
            cd docs
            mv /tmp/docs.tar.gz ./
            tar -zxf docs.tar.gz
            rm -f docs.tar.gz
            rm -rf /opt/maxkb/docs/*
            mv /tmp/docs/* /opt/maxkb/docs/
            /opt/nginx/bin/reload-nginx.sh
            rm -rf /tmp/docs*